/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ExamResult = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllResults' : IDL.Func([], [IDL.Vec(ExamResult)], ['query']),
  'getExamResult' : IDL.Func([IDL.Text], [ExamResult], ['query']),
  'submitResult' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ExamResult = IDL.Record({
    'username' : IDL.Text,
    'email' : IDL.Text,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllResults' : IDL.Func([], [IDL.Vec(ExamResult)], ['query']),
    'getExamResult' : IDL.Func([IDL.Text], [ExamResult], ['query']),
    'submitResult' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };